### ISSUE TITLE
Javascript shell outdated

### ISSUE THREAD

**Issue by jlpedrosa** [paralect/robomongo#772]
Hi All,

It's kind of an issue every time it's a new shell methods defined in mongo server as 
a) It's not defined in robomongo or
b) the implemtation is different in shell and can break something or don't work.

There should be a plug&play method to replace the shell implementation.

As an examples of a and b:

command: db.getUser
       mongo: works
       robomongo: TypeError: db.getUser is not a function (shell):1

command: db.changeUserPassword
       mongo: works
       robomongo: Changing password failed: not authorized for update on admin.system.users

best regards

**Comment by stennie** [comment]
@jlpedrosa This is a known issue, and being worked on for a [0.9.0 milestone](https://github.com/paralect/robomongo/milestones/Robomongo%200.9.0).

Thanks!

**Comment by schetnikovich** [comment]
@jlpedrosa Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Embedded shell is upgraded to MongoDB 3.2. Let us know, how it works for you. For any found issues, please create new ticket.
