### ISSUE TITLE
cmake 2.8.12.2 build failed

### ISSUE THREAD

**Issue by kkamkou** [paralect/robomongo#727]
This ticket is related to: #703

```
￫ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

￫ uname -a
Linux kkamkou-PC 3.16.0-28-generic #38-Ubuntu SMP Fri Dec 12 17:37:40 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

￫ dpkg -s libreadline-dev | grep Status
Status: install ok installed
                                                                                                                                                                                                                                              
￫ ls /usr/include/readline 
chardefs.h  history.h  keymaps.h  readline.h  rlconf.h  rlstdc.h  rltypedefs.h  tilde.h
```

**Comment by willm** [comment]
I'm having the same problem on ubuntu 14.04.1 LTS.

**Comment by willm** [comment]
I've been having the same issue on ubuntu 14.04 LTS. I've been digging into the problem, I don't know anything about CMake, but I think it has to do with commit 71d3973 - if you checkout this commit and build, you get the error. If you remove the line
```
cmake_policy(SET CMP0048 OLD)
```
in CMakeLists.txt, it works.

**Comment by pabx06** [comment]
@willm Solved cmake step 
but get building error when issuing  make 
```
[ 49%] Building CXX object src/third-party/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/__/src/ExternalLexer.cpp.o
In file included from /home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:24:0:
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:28:30: error: expected ‘)’ before ‘*’ token
 typedef void*(EXT_LEXER_DECL *GetLexerFunction)(unsigned int Index);
                              ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:28:30: error: expected initializer before ‘*’ token
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:29:29: error: expected ‘)’ before ‘*’ token
 typedef int (EXT_LEXER_DECL *GetLexerCountFn)();
                             ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:30:30: error: expected ‘)’ before ‘*’ token
 typedef void (EXT_LEXER_DECL *GetLexerNameFn)(unsigned int Index, char *name, int buflength);
                              ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:31:45: error: expected ‘)’ before ‘*’ token
 typedef LexerFactoryFunction(EXT_LEXER_DECL *GetLexerFactoryFunction)(unsigned int Index);
                                             ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:36:2: error: ‘GetLexerFactoryFunction’ does not name a type
  GetLexerFactoryFunction fneFactory;
  ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:47:27: error: ‘GetLexerFactoryFunction’ has not been declared
  virtual void SetExternal(GetLexerFactoryFunction fFactory, int index);
                           ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h: In constructor ‘ExternalLexerModule::ExternalLexerModule(int, LexerFunction, const char*, LexerFunction)’:
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:42:3: error: class ‘ExternalLexerModule’ does not have any field named ‘fneFactory’
   fneFactory(0) {
   ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp: At global scope:
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:38:39: error: variable or field ‘SetExternal’ declared void
 void ExternalLexerModule::SetExternal(GetLexerFactoryFunction fFactory, int index) {
                                       ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:38:39: error: ‘GetLexerFactoryFunction’ was not declared in this scope
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:38:73: error: expected primary-expression before ‘int’
 void ExternalLexerModule::SetExternal(GetLexerFactoryFunction fFactory, int index) {
                                                                         ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp: In constructor ‘LexerLibrary::LexerLibrary(const char*)’:
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:59:3: error: ‘GetLexerCountFn’ was not declared in this scope
   GetLexerCountFn GetLexerCount = (GetLexerCountFn)(sptr_t)lib->FindFunction("GetLexerCount");
   ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:59:19: error: expected ‘;’ before ‘GetLexerCount’
   GetLexerCountFn GetLexerCount = (GetLexerCountFn)(sptr_t)lib->FindFunction("GetLexerCount");
                   ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:61:7: error: ‘GetLexerCount’ was not declared in this scope
   if (GetLexerCount) {
       ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:66:4: error: ‘GetLexerNameFn’ was not declared in this scope
    GetLexerNameFn GetLexerName = (GetLexerNameFn)(sptr_t)lib->FindFunction("GetLexerName");
    ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:66:19: error: expected ‘;’ before ‘GetLexerName’
    GetLexerNameFn GetLexerName = (GetLexerNameFn)(sptr_t)lib->FindFunction("GetLexerName");
                   ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:67:4: error: ‘GetLexerFactoryFunction’ was not declared in this scope
    GetLexerFactoryFunction fnFactory = (GetLexerFactoryFunction)(sptr_t)lib->FindFunction("GetLexerFactory");
    ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:67:28: error: expected ‘;’ before ‘fnFactory’
    GetLexerFactoryFunction fnFactory = (GetLexerFactoryFunction)(sptr_t)lib->FindFunction("GetLexerFactory");
                            ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:76:33: error: ‘GetLexerName’ was not declared in this scope
     GetLexerName(i, lexname, 100);
                                 ^
/home/pbx06/tmp/robomongo/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:94:22: error: ‘fnFactory’ was not declared in this scope
     lex->SetExternal(fnFactory, i);
                      ^
make[2]: *** [src/third-party/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/__/src/ExternalLexer.cpp.o] Erreur 1
make[1]: *** [src/third-party/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/all] Erreur 2
make: *** [all] Erreur 2
```

**Comment by mastermind202** [comment]
I'm having a the issue with the build using Ubuntu 14.04 x64.  Can somebody suggest a way around the errors in ExternalLexer.h?

**Comment by willm** [comment]
@pabx06 I'm afraid I'm seeing the same issues

**Comment by stennie** [comment]
@mastermind202 @willm I'm testing Linux builds; will comment on the related issue #774 (if I can/can't repro the issue) since it has the full Cmake output. 

I also think it's best to support cmake 3.0+ rather than multiple versions. In theory the cmake_policy should be a warning in older versions rather than an error, but every permutation makes it harder to support.

Will close this as dupe so can continue investigation on #774. Thanks!
